### ISSUE TITLE
Query: Using Apple Home Key as Trigger and Required NFC Reader Type

### ISSUE THREAD

**Issue by tomkinane** [kormax/apple-home-key#3]
I'd like to inquire about whether it's possible to set up a trigger using the Apple Home key within the provided test environment. Additionally, could you clarify the type of NFC reader that is necessary for this?

**Comment by kormax** [comment]
Hello.

Regarding the trigger, if you're talking about the one added in IOS17 based on pass usage, it should work the same way. If you're talking about something else, custom implementation of a home key device can do anything you want, it's up to you.

Regarding the reader hardware. If you're not talking about the official one, of course.
HomeKey will be able to be implemented using any hardware that allows sending ISO7816 commands over ISODEP. So basically any PCSC reader or NFC module in existence.
For cool features such as express mode, you'll have to use reader hardware that allows ECP to be implemented. That limits you to using low-level NFC modules, like the ones used in Arduino-like projects.
For more info about that, I refer you to references section of this document or my profile.
