### ISSUE TITLE
Android Port

### ISSUE THREAD

**Issue by jappyjan** [kormax/apple-home-key#9]
Do you think with this knowledge we could create an app/service for android phones to work with these DIY homekey readers?
Our makerspace is thinking about adding these DIY readers to some of our systems and we would like to make it possible to be used by our android users too...

**Comment by kormax** [comment]
Hi,

Yes, I think this is entirely possible. In fact, when researching the protocol, I've written an Android app that helped me to debug protocol interaction with the real reader. Sadly, I don't have any code for it anymore, so won't be able to share.

There are two approaches in which this could be done (the hardest step - is to add your encryption key into a lock):
1) Using a custom HomeKit controller, one could provision an additional endpoint key into a lock, which will belong to that android device.
2) If you own a macOS device, you can extract your HomeKit issuer key from keychain, and use it to generate an attestation package, which the Android device will use to provision itself into a lock after performing FAST->STANDARD->ATTESTATION flow. (This is the way I've done it).


Having said that, I'd suggest you to wait for a little bit. The upcoming [Aliro](https://github.com/kormax/aliro) protocol, which is 90%+ based on HomeKey/CarKey (what Apple calls UnifiedAccess internally), will be supported by both iOS and Android devices officially. 

Matter will support Aliro-based locks natively, and looking into recent builds of Apple (IOS/Wallet/HomeKit), Google (GMS/Home/Wallet), Samsung (SmartThings/Wallet), they all will support provisioning of Aliro keys into the locks and respective Wallet applications. So there won't be any need to develop your own solution.

Aliro should come out somewhen during CES (Jan-Feb), with first consumer devices announced a bit later (Spring), and SDK/APIs shipping around that time too.
